### ISSUE TITLE
Plugin can't find editor

### ISSUE THREAD

**Issue by rob-mcdonald** [livestyle/issues#41]
Needed a refresh of Sublime. No logs available (seemed to close the log window and wiped any existing logs)

![screen shot 2015-08-10 at 14 39 54](https://cloud.githubusercontent.com/assets/13622137/9172868/45c334f6-3f6e-11e5-8942-44934f38d9c4.png)

**Comment by sergeche** [comment]
Check ST console for errors

**Comment by rob-mcdonald** [comment]
Where is it? I had the background.html open but it was empty when the crash occurred (it wasn't last time I checked). And there was no "Show Error" log on the  popup. I'll keep an eye out if it happens again, but that's only if the logs can be accessed!

**Comment by sergeche** [comment]
`View > Show Console` in Sublime Text

**Comment by rob-mcdonald** [comment]
Oh sorry, Sublime Text. Chrome logs went blank for a while so I started both ST and Chrome again. So this is probably of no use whatsoever, and the Sublime console is refreshed and I don't think there's a historical log:

[Current Chrome log](http://codeshare.io/doHEO)

If it happens again I'll remember to grab the ST log.

**Comment by isthatcentered** [comment]
Hello, I have the same issue on multiple computers, can't figure out what the problem is. Here's the ST log:
LiveStyle: Start app
LiveStyle: Client connection error: [Errno 10061] Unknown error
LiveStyle: Requested app restart
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x00000002F58F0A60>, <tornado.concurrent.Future object at 0x00000002F58F2198>)
Traceback (most recent call last):
  File "C:\Users\darky\Desktop\sublime\Data\Packages\LiveStyle\tornado.zip\tornado\ioloop.py", line 565, in _run_callback
    ret = callback()
  File "C:\Users\darky\Desktop\sublime\Data\Packages\LiveStyle\tornado.zip\tornado\stack_context.py", line 275, in null_wrapper
    return fn(_args, *_kwargs)
  File "C:\Users\darky\Desktop\sublime\Data\Packages\LiveStyle\livestyle-plugin.py", line 149, in restart_app
    logger.info('Restarting app because %s' % exc)
UnboundLocalError: local variable 'exc' referenced before assignment

**Comment by isthatcentered** [comment]
Ok, so I went back to the previous commit, and it's back to working. That's a relief as this is a tool I use for hours everyday !

**Comment by sergeche** [comment]
@isthatcentered oops... sorry, should work fine now

**Comment by isthatcentered** [comment]
Wow, that was very quick thanks a lot, that's amazing of you :)

This doesn't seem to do the trick though for some reason. 

The tornado part and end of debugging is different now. 

Your commit of 8f49 of Jul 29, 2015 does work fine. 

LiveStyle: Start app
Emmet: No need to update PyV8
LiveStyle: Client connection error: [Errno 10061] Unknown error
LiveStyle: Requested app restart
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x00000044E407E730>, <tornado.concurrent.Future object at 0x00000044E3FB81D0>)
Traceback (most recent call last):
  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\ioloop.py", line 565, in _run_callback
    ret = callback()
  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\stack_context.py", line 275, in null_wrapper
    return fn(_args, *_kwargs)
  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\livestyle-plugin.py", line 150, in restart_app
    logger.info('Restarting app because %s' % exc)
TypeError: not all arguments converted during string formatting

**Comment by sergeche** [comment]
@isthatcentered can you please try again now?

**Comment by isthatcentered** [comment]
Still doesn't work, but the error is different, and loops infinitly. 

Here's the log.

LiveStyle: Client connection error: [Errno 10061] Unknown error
LiveStyle: Requested app restart
LiveStyle: Restarting app because [Errno 10061] Unknown error
LiveStyle: ['Traceback (most recent call last):\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 631, in run\n    yielded = self.gen.throw(_sys.exc_info())\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\livestyle-plugin.py", line 247, in client_connect\n    raise e\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\livestyle-plugin.py", line 237, in client_connect\n    yield client.connect(port=port)\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 628, in run\n    value = future.result()\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 109, in result\n    raise_exc_info(self._exc_info)\n', '  File "<string>", line 3, in raise_exc_info\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 631, in run\n    yielded = self.gen.throw(_sys.exc_info())\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\livestyle\client.py", line 22, in connect\n    sock = yield tornado.websocket.websocket_connect(url)\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 628, in run\n    value = future.result()\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 111, in result\n    raise self._exception\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\stack_context.py", line 314, in wrapped\n    ret = fn(_args, *_kwargs)\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 157, in <lambda>\n    future, lambda future: callback(future.result()))\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 109, in result\n    raise_exc_info(self._exc_info)\n', '  File "<string>", line 3, in raise_exc_info\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 631, in run\n    yielded = self.gen.throw(*sys.exc_info())\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\tcpclient.py", line 164, in connect\n    af, addr, stream = yield connector.start()\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 628, in run\n    value = future.result()\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 111, in result\n    raise self._exception\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\tcpclient.py", line 103, in on_connect_done\n    stream = future.result()\n', '  File "C:\Users\darky\Desktop\Sublime\Data\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 111, in result\n    raise self._exception\n', 'ConnectionRefusedError: [Errno 10061] Unknown error\n']

**Comment by sergeche** [comment]
Hmm, what’s your OS and ST version?

**Comment by isthatcentered** [comment]
St3, windows 10. I can try on windows 7 or/and 8 tomorrow if you'd like.

**Comment by sergeche** [comment]
That would be great! I’ll try to install Win10 VM too

**Comment by isthatcentered** [comment]
Ok! Let me know if there's something you want besides the log.

**Comment by sergeche** [comment]
Is it possible that you have old LiveStyle extension? https://packagecontrol.io/packages/LiveStyle

**Comment by isthatcentered** [comment]
No, I use the zip from the repo, which I installed manually by dropping it inside packages. 

Same thing with windows 8, infinite loop:
(I'm assuming you are under windows 7 so I didn't try, but I'll be able to this afternoon if needed.)

Start app
LiveStyle: Client connection error: [Errno 10061] Unknown error
LiveStyle: Requested app restart
LiveStyle: Restarting app because [Errno 10061] Unknown error
LiveStyle: ['Traceback (most recent call last):\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 631, in run\n    yielded = self.gen.throw(_sys.exc_info())\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\livestyle-plugin.py", line 247, in client_connect\n    raise e\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\livestyle-plugin.py", line 237, in client_connect\n    yield client.connect(port=port)\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 628, in run\n    value = future.result()\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 109, in result\n    raise_exc_info(self._exc_info)\n', '  File "<string>", line 3, in raise_exc_info\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 631, in run\n    yielded = self.gen.throw(_sys.exc_info())\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\livestyle\client.py", line 22, in connect\n    sock = yield tornado.websocket.websocket_connect(url)\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 628, in run\n    value = future.result()\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 111, in result\n    raise self._exception\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\stack_context.py", line 314, in wrapped\n    ret = fn(_args, *_kwargs)\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 157, in <lambda>\n    future, lambda future: callback(future.result()))\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 109, in result\n    raise_exc_info(self._exc_info)\n', '  File "<string>", line 3, in raise_exc_info\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 631, in run\n    yielded = self.gen.throw(*sys.exc_info())\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\tcpclient.py", line 164, in connect\n    af, addr, stream = yield connector.start()\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\gen.py", line 628, in run\n    value = future.result()\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 111, in result\n    raise self._exception\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\tcpclient.py", line 103, in on_connect_done\n    stream = future.result()\n', '  File "C:\Users\Edouard\AppData\Roaming\Sublime Text 3\Packages\LiveStyle\tornado.zip\tornado\concurrent.py", line 111, in result\n    raise self._exception\n', 'ConnectionRefusedError: [Errno 10061] Unknown error\n']
LiveStyle: Start app

**Comment by sergeche** [comment]
Checked on Windows, should work fine now

**Comment by isthatcentered** [comment]
It does :) 
Thanks for the awesome work again !
