### ISSUE TITLE
LiveStyle doesnt save changes and showing "Destroy model for " in  Log error console

### ISSUE THREAD

**Issue by eissasoubhi** [livestyle/issues#86]
Hi ,

My LiveStyle doesnt save changes from browser to file nor from file to browser.
when i checked LiveStyle background page console. i had those messages.

![log-errors](https://cloud.githubusercontent.com/assets/4972714/12064023/0e5b69be-afb9-11e5-856b-204835cdb55b.jpg)

**Comment by eissasoubhi** [comment]
it worked after i uninstalled the extension and installed it again.

**Comment by sergeche** [comment]
FYI, `Destroy model` message indicates that LS decided to destroy internal LS state for given page for some reason (mostly to save some resources and in-house cleaning), but it will re-create it when you switch back to tab with that page.

For further debugging, you should look for exceptions and possible reasons why patch wasn’t applied on stylesheet. Most common issue for broken updates is closed messaging port which happens when Chrome extension was automatically updated. To solve this issue, simply close DevTools and reload page. I’ll try to explicitly indicate when you have to do so in LS popup

**Comment by netfox01** [comment]
OK THANKS
