### ISSUE TITLE
issue use browserSync Emmet  Chrome  SublimeText 

### ISSUE THREAD

**Issue by lionelgmc** [livestyle/issues#92]
Hi 
Since i search the best workflow i try to mix many refresh tools at once  in the same browser because i really like edit css in the browser for completion & real time rendering . 
i test BrowserSync to see if i can refresh the same css file open in ST manage by Emmet and BrowserSync ( that support spy and refresh also js and html and not only css). 
It seem not because the both tool inject javascript and selector  in the page locate in the browser ( i ll clik on emmet link and then try debug js aftert his post in chrome to test variable value ) .

regard's
![emmet_browsersync_issue](https://cloud.githubusercontent.com/assets/4058603/12080628/8733498e-b260-11e5-939c-123f29b8d9d0.png)

**Comment by sergeche** [comment]
LiveStyle doesn’t inject any scripts or stylesheets into page because it can handle everything as browser extension. Except for:
1. `data-livestyle-extension` attribute on `<html>` to tell Remote View client that browser support LiveStyle
2. Pages with `file://` protocol: it injects special iframe to work with CSSOM

Using other live edit tools with LiveStyle isn’t a good idea (at least for CSS) because these tools are too naive and can mess things up for LiveStyle
