### ISSUE TITLE
Works with CSS not Sass

### ISSUE THREAD

**Issue by djmtype** [livestyle/issues#94]
For the life of me, I can't get LiveStyle to work with scss files. Otherwise, It handles regular css files as intended. 

Tried with and without running `sass --watch scss:css` command beforehand. Verified LiveStyle is installed in Sublime and Chrome.
Using MAMP as a server, `localhost:8888/myproject/`

Mac OS 10.11.2
Sass 3.4.20
Chrome 47.0.2526.106

**Comment by sergeche** [comment]
> Make sure your document syntax in Sublime Text is set to SCSS

PS: you don't need to run any external tools like `sass:watch` with LiveStyle

**Comment by djmtype** [comment]
@sergeche My syntax is written as scss. I'm not sure if the problem is entirely with LiveStyle as it could be the latest version of Chrome. 

Kind of related, but off topic – Workspaces in Chrome Devtools worked fine before Chrome v47. Now, it doesn't entirely. The scss changes I make in Devtools are saved to my scss file, but it doesn't autoupdate the web page. Sometimes not even a manual refresh works until I make a new change to my scss from Sublime. Yet, my Devtool options are clearly set to _Auto-reload generated CSS_, _Enable CSS source maps_ and _Disable Cache_. Chrome v47 also added in a new option, _Display variable values inline while debugging_. Not sure what that does entirely.

**Comment by djmtype** [comment]
Also, wanted to add a screen capture of `main.scss` not showing up in the list; only `main.css`. Am I missing something?
https://cloudup.com/c8bJiqwJMgV

**Comment by sergeche** [comment]
I can see that your syntax is set to `Sass`, not SCSS. This is important because SASS is not supported yet (not a CSS-like syntax).

Since there are too many reports like that, I’ll tweak syntax detection in ST plugin to take file extension as syntax, then check applied grammar

**Comment by sergeche** [comment]
Just pushed update to Sublime Text plugin, should work with `*.scss` files even with `Sass` syntax

**Comment by djmtype** [comment]
@sergeche Sorry, I don't understand. Please explain. My syntax is written in `scss`, not `sass`. `sass` relies on indentations and without semicolons while `scss` is written more like vanilla `css`. My file extension is also set as `.scss`. Besides, there isn't any `scss` markup in my `scss` file. It's basically straight-up css I copied over from the HTML5 boilerplate.

**Comment by djmtype** [comment]
@sergeche Thank you, I appreciate it.

**Comment by sergeche** [comment]
> My syntax is written in scss, not sass

your document grammar (e.g. syntax highlighter) is set to `Sass`: http://cl.ly/2c15071N3k1O
I’m detecting document syntax from this grammar. After recent update, I’m using file extension in first place to detect document syntax

**Comment by djmtype** [comment]
@sergeche. Thanks for clearing that up. I see what you mean now. Had I chosen _CSS_ as the file type instead, LiveStyle would've detected my `.scss` file.

**Comment by smartcookiemedia** [comment]
Hey Guys,

Dont want to create a new ticket, but just stoked to try livestyle and just found out that it doesn't support SASS. I seems to be adding my modifications in the inspector to the bottom of the SCSS page, instead of in the original class / property.

Any update on this?

**Comment by sergeche** [comment]
Currently, project is on hold due to low interest from community

**Comment by smartcookiemedia** [comment]
Hi, Sergey

It seems to be detecting my scss file.  But, I seems to be adding my modifications in the inspector to the bottom of the SCSS page, instead of in the original class / property.  I wonder if the issue I am reporting is unrelated to what you are saying? Isn't sass without semicolons?  My file doesn't have that:

http://indigoestates.ca/wp-content/themes/blankslate/css/_base.scss

Pls advsise...

Thank you

**Comment by sergeche** [comment]
@smartcookiemedia the most common reasons why LiveStyle adds styles at the bottom of the source are:
1. The selector you’re editing in browser was generated by another file, e.g. it’s not the one opened in editor
2. LS failed to generate selector the same as official SCSS does, likely due to an error in LS. It’s a good idea to post an example with source code and selector you’re editing
3. You’re using optimizers like `cssmin` or something which might completely rebuild selector map in CSS so LS can’t find the origin of the selector
